# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import meshcored_pb2 as meshcored__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in meshcored_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MeshCoreDaemonStub:
    """Full control surface for the MeshCore daemon.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/meshcored.v1.MeshCoreDaemon/GetStatus',
                request_serializer=meshcored__pb2.Empty.SerializeToString,
                response_deserializer=meshcored__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetDeviceInfo = channel.unary_unary(
                '/meshcored.v1.MeshCoreDaemon/GetDeviceInfo',
                request_serializer=meshcored__pb2.Empty.SerializeToString,
                response_deserializer=meshcored__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.GetSelfInfo = channel.unary_unary(
                '/meshcored.v1.MeshCoreDaemon/GetSelfInfo',
                request_serializer=meshcored__pb2.Empty.SerializeToString,
                response_deserializer=meshcored__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.GetBattery = channel.unary_unary(
                '/meshcored.v1.MeshCoreDaemon/GetBattery',
                request_serializer=meshcored__pb2.Empty.SerializeToString,
                response_deserializer=meshcored__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.GetDeviceStats = channel.unary_unary(
                '/meshcored.v1.MeshCoreDaemon/GetDeviceStats',
                request_serializer=meshcored__pb2.Empty.SerializeToString,
                response_deserializer=meshcored__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.SetName = channel.unary_unary(
                '/meshcored.v1.MeshCoreDaemon/SetName',
                request_serializer=meshcored__pb2.SetNameRequest.SerializeToString,
                response_deserializer=meshcored__pb2.CommandResult.FromString,
                _registered_method=True)
        self.SetRadio = channel.unary_unary(
                '/meshcored.v1.MeshCoreDaemon/SetRadio',
                request_serializer=meshcored__pb2.SetRadioRequest.SerializeToString,
                response_deserializer=meshcored__pb2.CommandResult.FromString,
                _registered_method=True)
        self.SetTxPower = channel.unary_unary(
                '/meshcored.v1.MeshCoreDaemon/SetTxPower',
                request_serializer=meshcored__pb2.SetTxPowerRequest.SerializeToString,
                response_deserializer=meshcored__pb2.CommandResult.FromString,
                _registered_method=True)
        self.SetCoords = channel.unary_unary(
                '/meshcored.v1.MeshCoreDaemon/SetCoords',
                request_serializer=meshcored__pb2.SetCoordsRequest.SerializeToString,
                response_deserializer=meshcored__pb2.CommandResult.FromString,
                _registered_method=True)
        self.SetTime = channel.unary_unary(
                '/meshcored.v1.MeshCoreDaemon/SetTime',
                request_serializer=meshcored__pb2.SetTimeRequest.SerializeToString,
                response_deserializer=meshcored__pb2.CommandResult.FromString,
                _registered_method=True)
        self.SendAdvert = channel.unary_unary(
                '/meshcored.v1.MeshCoreDaemon/SendAdvert',
                request_serializer=meshcored__pb2.SendAdvertRequest.SerializeToString,
                response_deserializer=meshcored__pb2.CommandResult.FromString,
                _registered_method=True)
        self.Reboot = channel.unary_unary(
                '/meshcored.v1.MeshCoreDaemon/Reboot',
                request_serializer=meshcored__pb2.Empty.SerializeToString,
                response_deserializer=meshcored__pb2.CommandResult.FromString,
                _registered_method=True)
        self.ListContacts = channel.unary_unary(
                '/meshcored.v1.MeshCoreDaemon/ListContacts',
                request_serializer=meshcored__pb2.ListContactsRequest.SerializeToString,
                response_deserializer=meshcored__pb2.ListContactsResponse.FromString,
                _registered_method=True)
        self.SyncContacts = channel.unary_unary(
                '/meshcored.v1.MeshCoreDaemon/SyncContacts',
                request_serializer=meshcored__pb2.Empty.SerializeToString,
                response_deserializer=meshcored__pb2.CommandResult.FromString,
                _registered_method=True)
        self.RemoveContact = channel.unary_unary(
                '/meshcored.v1.MeshCoreDaemon/RemoveContact',
                request_serializer=meshcored__pb2.RemoveContactRequest.SerializeToString,
                response_deserializer=meshcored__pb2.CommandResult.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/meshcored.v1.MeshCoreDaemon/Ping',
                request_serializer=meshcored__pb2.PingRequest.SerializeToString,
                response_deserializer=meshcored__pb2.PingResponse.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_unary(
                '/meshcored.v1.MeshCoreDaemon/SendMessage',
                request_serializer=meshcored__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=meshcored__pb2.SendMessageResponse.FromString,
                _registered_method=True)
        self.SendChannelMessage = channel.unary_unary(
                '/meshcored.v1.MeshCoreDaemon/SendChannelMessage',
                request_serializer=meshcored__pb2.SendChannelMessageRequest.SerializeToString,
                response_deserializer=meshcored__pb2.SendMessageResponse.FromString,
                _registered_method=True)
        self.ListMessages = channel.unary_unary(
                '/meshcored.v1.MeshCoreDaemon/ListMessages',
                request_serializer=meshcored__pb2.ListMessagesRequest.SerializeToString,
                response_deserializer=meshcored__pb2.ListMessagesResponse.FromString,
                _registered_method=True)
        self.ListChannels = channel.unary_unary(
                '/meshcored.v1.MeshCoreDaemon/ListChannels',
                request_serializer=meshcored__pb2.Empty.SerializeToString,
                response_deserializer=meshcored__pb2.ListChannelsResponse.FromString,
                _registered_method=True)
        self.QueryPackets = channel.unary_unary(
                '/meshcored.v1.MeshCoreDaemon/QueryPackets',
                request_serializer=meshcored__pb2.QueryPacketsRequest.SerializeToString,
                response_deserializer=meshcored__pb2.QueryPacketsResponse.FromString,
                _registered_method=True)
        self.GetPacketStats = channel.unary_unary(
                '/meshcored.v1.MeshCoreDaemon/GetPacketStats',
                request_serializer=meshcored__pb2.PacketStatsRequest.SerializeToString,
                response_deserializer=meshcored__pb2.PacketStatsResponse.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/meshcored.v1.MeshCoreDaemon/StreamEvents',
                request_serializer=meshcored__pb2.StreamEventsRequest.SerializeToString,
                response_deserializer=meshcored__pb2.DaemonEvent.FromString,
                _registered_method=True)
        self.SendRawCommand = channel.unary_unary(
                '/meshcored.v1.MeshCoreDaemon/SendRawCommand',
                request_serializer=meshcored__pb2.RawCommandRequest.SerializeToString,
                response_deserializer=meshcored__pb2.RawCommandResponse.FromString,
                _registered_method=True)
        self.GetProxyStatus = channel.unary_unary(
                '/meshcored.v1.MeshCoreDaemon/GetProxyStatus',
                request_serializer=meshcored__pb2.Empty.SerializeToString,
                response_deserializer=meshcored__pb2.ProxyStatusResponse.FromString,
                _registered_method=True)


class MeshCoreDaemonServicer:
    """Full control surface for the MeshCore daemon.
    """

    def GetStatus(self, request, context):
        """Daemon & device status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSelfInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBattery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetName(self, request, context):
        """Device configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRadio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTxPower(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCoords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendAdvert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reboot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListContacts(self, request, context):
        """Contacts (backed by the daemon DB, which outgrows the device limit)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncContacts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """TRACE round trip; one five-second deadline including device command queueing.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Messaging
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendChannelMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChannels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryPackets(self, request, context):
        """Packet log & statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPacketStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Live event firehose (every meshcore event as JSON)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendRawCommand(self, request, context):
        """Escape hatch: raw companion-protocol command frame
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProxyStatus(self, request, context):
        """Proxy introspection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeshCoreDaemonServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=meshcored__pb2.Empty.FromString,
                    response_serializer=meshcored__pb2.StatusResponse.SerializeToString,
            ),
            'GetDeviceInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceInfo,
                    request_deserializer=meshcored__pb2.Empty.FromString,
                    response_serializer=meshcored__pb2.JsonResponse.SerializeToString,
            ),
            'GetSelfInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSelfInfo,
                    request_deserializer=meshcored__pb2.Empty.FromString,
                    response_serializer=meshcored__pb2.JsonResponse.SerializeToString,
            ),
            'GetBattery': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBattery,
                    request_deserializer=meshcored__pb2.Empty.FromString,
                    response_serializer=meshcored__pb2.JsonResponse.SerializeToString,
            ),
            'GetDeviceStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceStats,
                    request_deserializer=meshcored__pb2.Empty.FromString,
                    response_serializer=meshcored__pb2.JsonResponse.SerializeToString,
            ),
            'SetName': grpc.unary_unary_rpc_method_handler(
                    servicer.SetName,
                    request_deserializer=meshcored__pb2.SetNameRequest.FromString,
                    response_serializer=meshcored__pb2.CommandResult.SerializeToString,
            ),
            'SetRadio': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRadio,
                    request_deserializer=meshcored__pb2.SetRadioRequest.FromString,
                    response_serializer=meshcored__pb2.CommandResult.SerializeToString,
            ),
            'SetTxPower': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTxPower,
                    request_deserializer=meshcored__pb2.SetTxPowerRequest.FromString,
                    response_serializer=meshcored__pb2.CommandResult.SerializeToString,
            ),
            'SetCoords': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCoords,
                    request_deserializer=meshcored__pb2.SetCoordsRequest.FromString,
                    response_serializer=meshcored__pb2.CommandResult.SerializeToString,
            ),
            'SetTime': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTime,
                    request_deserializer=meshcored__pb2.SetTimeRequest.FromString,
                    response_serializer=meshcored__pb2.CommandResult.SerializeToString,
            ),
            'SendAdvert': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAdvert,
                    request_deserializer=meshcored__pb2.SendAdvertRequest.FromString,
                    response_serializer=meshcored__pb2.CommandResult.SerializeToString,
            ),
            'Reboot': grpc.unary_unary_rpc_method_handler(
                    servicer.Reboot,
                    request_deserializer=meshcored__pb2.Empty.FromString,
                    response_serializer=meshcored__pb2.CommandResult.SerializeToString,
            ),
            'ListContacts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListContacts,
                    request_deserializer=meshcored__pb2.ListContactsRequest.FromString,
                    response_serializer=meshcored__pb2.ListContactsResponse.SerializeToString,
            ),
            'SyncContacts': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncContacts,
                    request_deserializer=meshcored__pb2.Empty.FromString,
                    response_serializer=meshcored__pb2.CommandResult.SerializeToString,
            ),
            'RemoveContact': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveContact,
                    request_deserializer=meshcored__pb2.RemoveContactRequest.FromString,
                    response_serializer=meshcored__pb2.CommandResult.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=meshcored__pb2.PingRequest.FromString,
                    response_serializer=meshcored__pb2.PingResponse.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=meshcored__pb2.SendMessageRequest.FromString,
                    response_serializer=meshcored__pb2.SendMessageResponse.SerializeToString,
            ),
            'SendChannelMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendChannelMessage,
                    request_deserializer=meshcored__pb2.SendChannelMessageRequest.FromString,
                    response_serializer=meshcored__pb2.SendMessageResponse.SerializeToString,
            ),
            'ListMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMessages,
                    request_deserializer=meshcored__pb2.ListMessagesRequest.FromString,
                    response_serializer=meshcored__pb2.ListMessagesResponse.SerializeToString,
            ),
            'ListChannels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChannels,
                    request_deserializer=meshcored__pb2.Empty.FromString,
                    response_serializer=meshcored__pb2.ListChannelsResponse.SerializeToString,
            ),
            'QueryPackets': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryPackets,
                    request_deserializer=meshcored__pb2.QueryPacketsRequest.FromString,
                    response_serializer=meshcored__pb2.QueryPacketsResponse.SerializeToString,
            ),
            'GetPacketStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPacketStats,
                    request_deserializer=meshcored__pb2.PacketStatsRequest.FromString,
                    response_serializer=meshcored__pb2.PacketStatsResponse.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=meshcored__pb2.StreamEventsRequest.FromString,
                    response_serializer=meshcored__pb2.DaemonEvent.SerializeToString,
            ),
            'SendRawCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SendRawCommand,
                    request_deserializer=meshcored__pb2.RawCommandRequest.FromString,
                    response_serializer=meshcored__pb2.RawCommandResponse.SerializeToString,
            ),
            'GetProxyStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProxyStatus,
                    request_deserializer=meshcored__pb2.Empty.FromString,
                    response_serializer=meshcored__pb2.ProxyStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'meshcored.v1.MeshCoreDaemon', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('meshcored.v1.MeshCoreDaemon', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MeshCoreDaemon:
    """Full control surface for the MeshCore daemon.
    """

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshcored.v1.MeshCoreDaemon/GetStatus',
            meshcored__pb2.Empty.SerializeToString,
            meshcored__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshcored.v1.MeshCoreDaemon/GetDeviceInfo',
            meshcored__pb2.Empty.SerializeToString,
            meshcored__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSelfInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshcored.v1.MeshCoreDaemon/GetSelfInfo',
            meshcored__pb2.Empty.SerializeToString,
            meshcored__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBattery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshcored.v1.MeshCoreDaemon/GetBattery',
            meshcored__pb2.Empty.SerializeToString,
            meshcored__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshcored.v1.MeshCoreDaemon/GetDeviceStats',
            meshcored__pb2.Empty.SerializeToString,
            meshcored__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshcored.v1.MeshCoreDaemon/SetName',
            meshcored__pb2.SetNameRequest.SerializeToString,
            meshcored__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRadio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshcored.v1.MeshCoreDaemon/SetRadio',
            meshcored__pb2.SetRadioRequest.SerializeToString,
            meshcored__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTxPower(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshcored.v1.MeshCoreDaemon/SetTxPower',
            meshcored__pb2.SetTxPowerRequest.SerializeToString,
            meshcored__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCoords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshcored.v1.MeshCoreDaemon/SetCoords',
            meshcored__pb2.SetCoordsRequest.SerializeToString,
            meshcored__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshcored.v1.MeshCoreDaemon/SetTime',
            meshcored__pb2.SetTimeRequest.SerializeToString,
            meshcored__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendAdvert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshcored.v1.MeshCoreDaemon/SendAdvert',
            meshcored__pb2.SendAdvertRequest.SerializeToString,
            meshcored__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reboot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshcored.v1.MeshCoreDaemon/Reboot',
            meshcored__pb2.Empty.SerializeToString,
            meshcored__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListContacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshcored.v1.MeshCoreDaemon/ListContacts',
            meshcored__pb2.ListContactsRequest.SerializeToString,
            meshcored__pb2.ListContactsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncContacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshcored.v1.MeshCoreDaemon/SyncContacts',
            meshcored__pb2.Empty.SerializeToString,
            meshcored__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshcored.v1.MeshCoreDaemon/RemoveContact',
            meshcored__pb2.RemoveContactRequest.SerializeToString,
            meshcored__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshcored.v1.MeshCoreDaemon/Ping',
            meshcored__pb2.PingRequest.SerializeToString,
            meshcored__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshcored.v1.MeshCoreDaemon/SendMessage',
            meshcored__pb2.SendMessageRequest.SerializeToString,
            meshcored__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendChannelMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshcored.v1.MeshCoreDaemon/SendChannelMessage',
            meshcored__pb2.SendChannelMessageRequest.SerializeToString,
            meshcored__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshcored.v1.MeshCoreDaemon/ListMessages',
            meshcored__pb2.ListMessagesRequest.SerializeToString,
            meshcored__pb2.ListMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListChannels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshcored.v1.MeshCoreDaemon/ListChannels',
            meshcored__pb2.Empty.SerializeToString,
            meshcored__pb2.ListChannelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryPackets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshcored.v1.MeshCoreDaemon/QueryPackets',
            meshcored__pb2.QueryPacketsRequest.SerializeToString,
            meshcored__pb2.QueryPacketsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPacketStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshcored.v1.MeshCoreDaemon/GetPacketStats',
            meshcored__pb2.PacketStatsRequest.SerializeToString,
            meshcored__pb2.PacketStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/meshcored.v1.MeshCoreDaemon/StreamEvents',
            meshcored__pb2.StreamEventsRequest.SerializeToString,
            meshcored__pb2.DaemonEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendRawCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshcored.v1.MeshCoreDaemon/SendRawCommand',
            meshcored__pb2.RawCommandRequest.SerializeToString,
            meshcored__pb2.RawCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProxyStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshcored.v1.MeshCoreDaemon/GetProxyStatus',
            meshcored__pb2.Empty.SerializeToString,
            meshcored__pb2.ProxyStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
